# Configuration du bundle de vérification d'email
symfonycasts_verify_email:
    # Durée de vie du token de vérification en secondes
    lifetime: 3600  # 1 heure
    
    # Optionnel : personnaliser le nom du paramètre dans l'URL
    # query_parameter: 'token'
    
    # Optionnel : personnaliser le nom du paramètre d'expiration
    # expires_parameter: 'expires'
    
    # Optionnel : personnaliser le nom du paramètre de signature  
    # signature_parameter: 'signature'